# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d1640087a435b0566cc375d958bd50ef9595bc1ecd70156f00bd32482c752774b81aec9611f89fd350fe576acb4f6bf225b0b3029005eba9c5198cf0df66bea

test:
  secret_key_base: 61a245b5eba5c20a2eec20497d5b66462634acfb25176c15838c71839fca56f7f15430ae5d06fe6c33f7dfb547e53def55bdff185b490fa39e858fc85c82f55c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
